"""Initial migration

Revision ID: 3000a8636fb0
Revises: 
Create Date: 2026-04-10 23:29:55.120098
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3000a8636fb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca_firms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.Enum('ANDHRA_PRADESH', 'ARUNACHAL_PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL_PRADESH', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA_PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL_NADU', 'TELANGANA', 'TRIPURA', 'UTTAR_PRADESH', 'UTTARAKHAND', 'WEST_BENGAL', 'ANDAMAN_NICOBAR', 'CHANDIGARH', 'DADRA_NAGAR_HAVELI', 'DELHI', 'JAMMU_KASHMIR', 'LADAKH', 'LAKSHADWEEP', 'PUDUCHERRY', name='indianstate'), nullable=True),
    sa.Column('subscription_tier', sa.Enum('CA_STARTER', 'CA_PROFESSIONAL', 'CA_ENTERPRISE', 'MSME_DIRECT', name='subscriptiontier'), nullable=True),
    sa.Column('max_client_profiles', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('custom_brand_name', sa.String(length=255), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('secondary_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetch_method', sa.String(length=50), nullable=False),
    sa.Column('fetch_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('scraper_module_name', sa.String(length=100), nullable=False),
    sa.Column('requires_pdf_extraction', sa.Boolean(), nullable=True),
    sa.Column('requires_ocr_fallback', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_code')
    )
    op.create_table('scraper_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=True),
    sa.Column('new_documents', sa.Integer(), nullable=True),
    sa.Column('changed_documents', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CA_REVIEWER', 'CA_FIRM_ADMIN', 'MSME_OWNER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('ca_firm_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ca_firm_id'], ['ca_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.Enum('SOLE_PROPRIETORSHIP', 'PARTNERSHIP_FIRM', 'LLP', 'PRIVATE_LIMITED', 'PUBLIC_LIMITED', 'HUF', 'TRUST_SOCIETY', 'OPC', name='businesstype'), nullable=False),
    sa.Column('industry_sector', sa.Enum('MANUFACTURING', 'TRADING_RETAIL', 'FOOD_BEVERAGE', 'IT_SOFTWARE', 'PROFESSIONAL_SERVICES', 'HEALTHCARE_PHARMA', 'CONSTRUCTION_REALESTATE', 'LOGISTICS_TRANSPORT', 'FINANCIAL_SERVICES', 'EDUCATION', 'AGRICULTURE', 'TEXTILE', 'OTHER', name='industrysector'), nullable=False),
    sa.Column('industry_sector_other', sa.String(length=255), nullable=True),
    sa.Column('nic_code', sa.String(length=10), nullable=True),
    sa.Column('registration_state', sa.Enum('ANDHRA_PRADESH', 'ARUNACHAL_PRADESH', 'ASSAM', 'BIHAR', 'CHHATTISGARH', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL_PRADESH', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'MADHYA_PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL_NADU', 'TELANGANA', 'TRIPURA', 'UTTAR_PRADESH', 'UTTARAKHAND', 'WEST_BENGAL', 'ANDAMAN_NICOBAR', 'CHANDIGARH', 'DADRA_NAGAR_HAVELI', 'DELHI', 'JAMMU_KASHMIR', 'LADAKH', 'LAKSHADWEEP', 'PUDUCHERRY', name='indianstate'), nullable=False),
    sa.Column('operating_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('udyam_category', sa.Enum('MICRO', 'SMALL', 'MEDIUM', 'NOT_REGISTERED', name='udyamcategory'), nullable=False),
    sa.Column('employee_count_band', sa.Enum('BAND_0_5', 'BAND_6_10', 'BAND_11_20', 'BAND_21_50', 'BAND_51_100', 'BAND_101_200', 'BAND_200_PLUS', name='employeecountband'), nullable=False),
    sa.Column('annual_turnover_band', sa.Enum('BELOW_20L', 'L20_TO_L40', 'L40_TO_1_5CR', 'CR1_5_TO_5CR', 'CR5_TO_10CR', 'CR10_TO_50CR', 'ABOVE_50CR', name='turnoverband'), nullable=False),
    sa.Column('gst_status', sa.Enum('REGULAR', 'COMPOSITION', 'UNREGISTERED', 'EXPORT_LUT', 'SEZ', name='gststatus'), nullable=False),
    sa.Column('has_export_activity', sa.Boolean(), nullable=True),
    sa.Column('has_manufacturing_unit', sa.Boolean(), nullable=True),
    sa.Column('handles_food_products', sa.Boolean(), nullable=True),
    sa.Column('existing_licences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ca_firm_id', sa.UUID(), nullable=True),
    sa.Column('preferred_language', sa.Enum('ENGLISH', 'HINDI', 'KANNADA', 'TAMIL', 'TELUGU', 'MARATHI', 'GUJARATI', name='preferredlanguage'), nullable=True),
    sa.Column('alert_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ca_firm_id'], ['ca_firms.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bp_business_type', 'business_profiles', ['business_type'], unique=False)
    op.create_index('ix_bp_ca_firm', 'business_profiles', ['ca_firm_id'], unique=False)
    op.create_index('ix_bp_gst_status', 'business_profiles', ['gst_status'], unique=False)
    op.create_index('ix_bp_registration_state', 'business_profiles', ['registration_state'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_pdf_s3_key', sa.String(length=500), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('FETCHED', 'EXTRACTING', 'EXTRACTED', 'PROCESSING', 'PROCESSED', 'REVIEW_PENDING', 'APPROVED', 'REJECTED', 'FAILED', name='documentstatus'), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('llm_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('approved_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('ix_doc_source_url', 'documents', ['source_id', 'url'], unique=False)
    op.create_index('ix_doc_status', 'documents', ['status'], unique=False)
    op.create_table('compliance_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compliance_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary_plain_english', sa.Text(), nullable=True),
    sa.Column('what_you_need_to_do', sa.Text(), nullable=True),
    sa.Column('regulatory_body', sa.String(length=100), nullable=False),
    sa.Column('regulation_reference', sa.String(length=300), nullable=True),
    sa.Column('notification_number', sa.String(length=100), nullable=True),
    sa.Column('applicable_if', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('not_applicable_if', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('due_date_logic', sa.String(length=300), nullable=True),
    sa.Column('alert_trigger_days_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('penalty_for_non_compliance', sa.Text(), nullable=True),
    sa.Column('urgency_level', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='urgencylevel'), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=True),
    sa.Column('amends_compliance_id', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compliance_id')
    )
    op.create_index('ix_ci_deadline', 'compliance_items', ['compliance_deadline'], unique=False)
    op.create_index('ix_ci_regulatory_body', 'compliance_items', ['regulatory_body'], unique=False)
    op.create_index('ix_ci_urgency', 'compliance_items', ['urgency_level'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('compliance_item_id', sa.UUID(), nullable=False),
    sa.Column('business_profile_id', sa.UUID(), nullable=False),
    sa.Column('alert_title', sa.String(length=300), nullable=False),
    sa.Column('alert_body', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('ENGLISH', 'HINDI', 'KANNADA', 'TAMIL', 'TELUGU', 'MARATHI', 'GUJARATI', name='preferredlanguage'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'ACKNOWLEDGED_NOTED', 'ACKNOWLEDGED_DONE', 'ACKNOWLEDGED_NOT_APPLICABLE', 'FAILED', name='alertstatus'), nullable=True),
    sa.Column('acknowledgement_note', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('compliance_item_id', 'business_profile_id', name='uq_alert_compliance_business')
    )
    op.create_index('ix_alert_business', 'alerts', ['business_profile_id'], unique=False)
    op.create_index('ix_alert_compliance', 'alerts', ['compliance_item_id'], unique=False)
    op.create_index('ix_alert_status', 'alerts', ['status'], unique=False)
    op.create_table('delivery_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('WHATSAPP', 'EMAIL', 'SMS', name='deliverychannel'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dl_alert', 'delivery_logs', ['alert_id'], unique=False)
    op.create_index('ix_dl_channel', 'delivery_logs', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dl_channel', table_name='delivery_logs')
    op.drop_index('ix_dl_alert', table_name='delivery_logs')
    op.drop_table('delivery_logs')
    op.drop_index('ix_alert_status', table_name='alerts')
    op.drop_index('ix_alert_compliance', table_name='alerts')
    op.drop_index('ix_alert_business', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_ci_urgency', table_name='compliance_items')
    op.drop_index('ix_ci_regulatory_body', table_name='compliance_items')
    op.drop_index('ix_ci_deadline', table_name='compliance_items')
    op.drop_table('compliance_items')
    op.drop_index('ix_doc_status', table_name='documents')
    op.drop_index('ix_doc_source_url', table_name='documents')
    op.drop_index('ix_doc_content_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_bp_registration_state', table_name='business_profiles')
    op.drop_index('ix_bp_gst_status', table_name='business_profiles')
    op.drop_index('ix_bp_ca_firm', table_name='business_profiles')
    op.drop_index('ix_bp_business_type', table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scraper_runs')
    op.drop_table('sources')
    op.drop_table('ca_firms')
    # ### end Alembic commands ###
